name: anon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For authentication.
  firebase_auth: ^1.1.0

  # To manage firebase.
  firebase_core: ^1.0.3

  # Manage user data.
  cloud_firestore: ^1.0.5

  # For state managment.
  flutter_bloc: ^7.0.0

  # Console logger for clear prints.
  logger: ^1.0.0

  # Markdown view for posts.
  flutter_markdown: ^0.6.1

  url_launcher: ^6.0.3

  # To save data to local db.
  shared_preferences: ^2.0.5

  # Special copy of https://pub.dev/packages/field_suggestion.
  # Made to make able search value from custom model class and for different UI.
  field_suggestion:
    git:
      url: git://github.com/theiskaa/field_suggestion.git
      ref: special-for-anon

  cupertino_icons: ^1.0.2
  mockito:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/