name: anon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For authentication.
  firebase_auth: ^1.1.0

  # To manage firebase.
  firebase_core: ^1.0.3

  # Manage user data.
  cloud_firestore: ^1.0.5

  # For state managment.
  flutter_bloc: ^7.0.0

  # Console logger for clear prints.
  logger: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/